const PHRASES = [
    "Let's go to the mall everybody! Go! C'mon Jessica, C'mon Tori let's go to the mall you won't be sorry. Put on your jelly-bracelets and your cool graffiti-coat at the mall havin' fun is what its all about. I haven't done my homework yet... That's okay. And you know how my parents get... Whatever. I don't care 'cause all my friends are gonna be there Everybody come and play Throw every last care away Let's go to the mall... Today. Chloe, mouse, I love it. There's this boy I like Met him at the food court. He's got hair like Brettsy and he does jumps on his skateboard. I hope he asks me out take me to my favourite spot. It'll be just him and me. But don't forget the robot. Dad says I'm too young to date. Lame. But baby I don't wanna wait. I don't wanna wait. Let's do it. That's okay I'm gonna rock your body anyway. I'm gonna rock your body till the Canada Day. Everybody come and play Throw every last care away Let's go to the mall... Today. I went to the mall with a couple of friends. I had a whole week's allowance to spend. I want hoop earrings and a Benetton shirt. We came here to shop and we came here to flirt. I turned around and who should I see? Prime Minister Brian Mulrooney. He said, Young lady I don't approve. So I had to get down and bust trees sweet moves. Hey Fred... c'mon... let's go to the mall! Let's go to the mall everybody! Everybody come and play Throw every last care away Let's go to the mall... Today. Everybody loves the mall! Everybody come and play Yeah! Throw every last care away I love my hoop earrings. Let's go to the mall... Today. Today. Let's go to the mall.",
    "The stars are falling from the sky And you're the reason why The moon is shining on your face And I finally think it's found its place Cause maybe, baby, I just wanna do you, do you Do you wanna do me, do me Underneath the moonlight The moonlight tonight? And now we're hiding in my car I let you see my scars Escape the dark for just one night Your heart makes me explode with light Baby, maybe Maybe I will steal you, steal you Just so I can feel you, feel you Maybe that will heal you, heal you On the inside Underneath the willow tree Wearing nothing else but me Babe, I just wanna do you Do you wanna do me Underneath the moonlight? Hayley, Hayley This is why you need me, relieve me Close your eyes and breath deep, breath deep Let me set your mind free till the sunrise",
    "Cuando el gato no esta en casa empiezan los carnavales y la comparsa Los ratones guarachean y se botan pa la calle pa que to el mundo los vea Una pila e ratas flacas de cloaca arrollando por to el muro e la maleca Los ratones calentando la piragua y las ratas en la tribuna haciendose los repa Gato dice Miau miau mia miau Ese es el gato y viene super asfixiao anda con un tigre y con dos leones barriendo las ratas y a to los ratones Gato dice Miau miau mia miau Ese es el gato y viene super asfixiao anda con un tigre y con dos leones barriendo las ratas y a to los ratones ohhh Dejense de gracia que nos mordemos dejense de gracia que somos de zona dejense de gracia voa barrer a uno dejense de gracia ya con la coronaaaa con la coronaaaa con la coronaaaa po po po por eso papa suelta la corona tu veo anda oye como yo no estaba ustedes andaban inflanda todos recojan lpos chelines que es BAJANDA BAJANDA, BAJANDA BAJANDA andanda andas acabanda andanda Tu lo que tienes que borrarte el banga BAJANDA,BAJANDA BAJANDA andanda andas acabanda andanda Oye que sueltes la corona veo anda suelta la corona y te quito a tu pocha Y cuando te vuelvas a hacer el asfixiao ya me dijo el entunakua que te va a meter la mocha BAJANDA Oye que sueltes la corona yoooo suelta sueltala tu veo anda BAJANDA Que yo soy el originanda ustedes estan copianda ustedes estan inflanda BAJANDA Ahora se va a calentar la yarda Ahora es que yo quiero ver su guapanga BAJANDA Ahora manda, mete mete, manda y si no borrate el banga BAJANDA Que no se me hagan mas los ñangas te coge el entunakua y Jan Carlo el itanga BAJANDA Tu sabes por que es BAJANDA porque esto es 100 pa abajo esta es mi banda BAJANDA 100 pa abajo, 100 pa abajo Pregunta por la Vibora mi banda BAJANDA Esto es 100 pa abajo es BAJANDA y pregunta por el pardo mi banda Jee, es el nankabia, el itanga you el entunakua la banda you Pa que no te me hagas mas el ñanga Una pila de ñanga que te van a hacer BAJANDA you youuuu los 100 ba abajo que te van a hacer bajanda you, el de hacen po po po po el de hacen po po po po el rasta soy yo el reyyyy, fuck you",
    "I found a way, to that light Ah, fuck the money, I found the li-ight I said I found a way, to that light To that light, I got it right I said I found a way, to that light Ah, fuck the money, I found the li-ight I said I found a way, to that light To that light, I got it right I said I found a way, to that light Ah, fuck the money, I found the li-ight I said I found a way, to that light To that light, to that light Blowin' all this cash on the things that never last I don't want it, you can have it Countin' up this bag while I'm smokin' out the bag With my brother, yo roll another Eyes bloodshed, marijuana Starin' at the eyes of my karma I'm bumpin' Michael Jackson and Nirvana I'm tryna find my way to Madonna I said I found a way, to that light Ah, fuck the money, I found the li-ight I said I found a way, to that light To that light, I got it right I said I found a way, to that light Ah, fuck the money, I found the li-ight I said I found a way, to that light To that light, I got it right Now I see the signs, that's why I'm pressin' decline When you call me, ain't tryna hear it (hello?) I turned to the guy that you said I couldn't, right? Like it's magic, I'm disappearin' Head lookin' down at my call log I've been doin' things how I wanna Focused on the fam and mi casa What you talkin' 'bout? What you thought, love? I said I found a way, to that light Ah, fuck the money, I found the li-ight I said I found a way, to that light To that light, I got it right I said I found a way, to that light Ah, fuck the money, I found the li-ight I said I found a way, to that light To that light, I got it right",
    "'Cause you know in the old days They couldn't say the shit they wanted to say They had to fake orgasms and shit We can tell niggas today: 'Hey, I wanna cum, mothafucka!' You're such a fuckin' ho, I love it (I love it) You're such a fuckin' ho, I love it (I love it) You're such a fuckin' ho, I love it (Love it, love it) (I'ma fuck a bitch, tell her cousin) Your boyfriend is a dork, McLovin (Dork) I just pulled up in a Ghost (Ghost) Fucked that bitch up out in London (Up out in) Then I fucked up on her cousin Or her sister, I don't know nothin' (Uh-uh, woo) And my niggas gettin' ignorant Like a lighter, bitch, we ignant (Ignant, yeah) All this water on my neck Look like I fell when I went fishin' (Fell!) So much diamonds on my bust down Ooh, fuck, what's the time? (Where we at?) Me and Smokepurpp sippin' drank (Purpp!) Ooh, fuck, she take lines (Lines) You're such a fuckin' ho, I love it (I love it, scoop!) You're such a fuckin' ho, I love it (I love it) You're such a fuckin' ho When the first time they ask you if you want sparklin' or still? Why you tryna act like you was drinkin' sparklin' water 'fore you came out here? You're such a fuckin' h— I'm a sick fuck, I like a quick fuck (Whoop!) I'm a sick fuck, I like a quick fuck (Whoop!) I'm a sick fuck, I like a quick fuck (Whoop!) I'm a sick fuck, I like a quick fuck (Whoop!) I'm a sick fuck, I like a quick fuck I like my dick sucked, I'll buy you a sick truck I'll buy you some new tits, I'll get you that nip-tuck How you start a family? The condom slipped up I'm a sick fuck, I'm inappropriate I like hearin' stories, I like that ho shit I wanna hear mo' shit, I like the ho shit Send me some mo' shit, you triflin' ho bitch (Bitch, bitch, bitch) You're such a fuckin' ho, I love it (I love it) You're such a fuckin' ho, I love it (I love it) 'Cause you know in the old days They couldn't say the shit they wanted to say They had to fake orgasms and shit We can tell niggas today: 'Hey, I wanna cum, mothafucka!'",
    "Yo, Big Shaq, the one and only Man's not hot, never hot Skrrat, skidi-kat-kat Boom Two plus two is four, minus one that's three, quick maths Everyday man's on the block, smoke trees See your girl in the park, that girl is a uckers When the ting went quack-quack-quack, you man were ducking (you man ducked) Hold tight, Asnee (my brotha), he's got the pumpy (big ting) Hold tight, my man (my guy), he's got the frisbee I trap, trap, trap on the phone, movin' that cornflakes Rice Krispies, hold tight my girl, Whitney (my G) On the road doin' ten toes, like my toes (like my toes) You man thought I froze, I see a peng girl, then I pose (chilin') If she ain't on it, I ghost, hah, look at your nose (check your nose fam) You donut, nose long like garden hose I tell her man's not hot, I tell her man's not hot The girl told me, 'Take off your jacket' I said, 'Babes, man's not hot' (never hot) I tell her man's not hot (never hot) I tell her man's not hot (never hot) The girl told me, 'Take off your jacket' I said, 'Babes, man's not hot' (never hot) Hop out the four-door with the .44, it was one, two, three and four (us man) Chillin' in the corridor (yo), your dad is forty-four And he's still callin' man for a draw (look at him), let him know When I see him, I'm gonna spin his jaw (finished) Take man's Twix by force (take it), send man shop by force (send him) Your girl knows I've got the sauce (flexin'), no ketchup (none) Just sauce (saucy), raw sauce Ah, yo, boom, ah The ting goes skrrrahh, pap, pap, ka-ka-ka Skidiki-pap-pap, and a pu-pu-pudrrrr-boom Skya, du-du-ku-ku-dun-dun Poom, poom, you dun know I tell her man's not hot (man's not), I tell her man's not hot (never hot) The girl told me, 'Take off your jacket' I said, 'Babes, man's not hot' (never hot) I tell her man's not hot (never hot) I tell her man's not hot (never hot) The girl told me, 'Take off your jacket' I said, 'Babes, man's not hot' Man can never be hot (never hot), perspiration ting (spray dat) Lynx Effect (come on), you didn't hear me did you? (nah) Use roll-on (use that), or spray But either way, A-B-C-D (alphabet ting) The ting goes skrrrahh, pap, pap, ka-ka-ka Skidiki-pap-pap, and a pu-pu-pudrrrr-boom Skya, du-du-ku-ku-dun-dun Poom, poom You dun know, Big Shaq Man's not hot I tell her man's not hot (never hot) Forty degrees and man's not hot (come on) Yo, in the sauna, man's not hot (never hot) Yeah, skidika-pap-pap",
    "Aha, aha, hahaha, hahaha-ha Brlrl, brlrl, haha Aha, aha, hahaha, hahaha-ha Brlrl, brlrl, haha Aha, aha, hahaha, hahaha-ha Brlrl, brlrl, haha Aha, aha, hahaha, hahaha-ha Brlrl, brlrl, haha Chandram Brambachandra Chandra Bendram Chandram Brambachandra Chandra Bendram Chandram Brambachandra Chandra Bendram Chandram Brambachandra Chandra Bendram  Aha, aha, hahaha, hahaha-ha Brlrl, brlrl, haha Aha, aha, hahaha, hahaha-ha Brlrl, brlrl, haha Aha, aha, hahaha, hahaha-ha Brlrl, brlrl, haha Aha, aha, hahaha, hahaha-ha Brlrl, brlrl, haha Chandram Brambachandra Chandra Bendram Chandram Brambachandra Chandra Bendram Chandram Brambachandra Chandra Bendram Chandram Brambachandra Chandra Bendram"
];

function speak(index){
    console.log(PHRASES);
    if(index == null){
        phrase = getRandomArrayEntry(PHRASES);
        window.speechSynthesis.speak(new window.SpeechSynthesisUtterance(phrase))
    }else{
        phrase = PHRASES[index];
        window.speechSynthesis.speak(new window.SpeechSynthesisUtterance(phrase))
    }
}

function stopSpeak(){
    window.speechSynthesis.cancel();
}

function getRandomArrayEntry(array){
    var index = Math.floor(Math.random() * (array.length));
    return array[index];
}